#!/bin/sh
set -eu

cd "$(dirname "$(realpath "$0")")"

name="$(cargo metadata --format-version=1 | \
    python -c \
    "import sys, json; print(json.load(sys.stdin)['packages'][0]['name'])"\
    )"

if ! [ -e HXRT216.zip ]; then
    wget https://www.japheth.de/Download/HX/HXRT216.zip || exit 1
fi

if ! [ -d HXRT216 ]; then
    mkdir HXRT216 || exit 1
    unzip -d HXRT216 HXRT216.zip || exit 1
fi

cargo +nightly build \
    --verbose \
    -Z build-std=core,alloc,panic_abort \
    -Z build-std-features=panic_immediate_abort \
    --target "i686-pc-windows-gnu" \
    --release || exit 1

mkdir -p target/i686-pc-dos-hxrt/release || exit 1
cp -f target/i686-pc-windows-gnu/release/"$name".exe \
    target/i686-pc-dos-hxrt/release/"$name".exe \
    || exit 1
wine HXRT216/BIN/PESTUB.EXE -v -n -x -s \
    target/i686-pc-dos-hxrt/release/"$name".exe \
    HXRT216/BIN/DPMIST32.BIN \
    || exit 1
cp -f HXRT216/BIN/DPMILD32.EXE \
    target/i686-pc-dos-hxrt/release \
    || exit 1
